model_name_or_path: instella-3b-sft-math-stage1
use_flash_attn: true
tokenizer_name: amd/Instella-3B-Math
use_slow_tokenizer: false
dataset_name: koajoel/AM-DeepSeek-R1-Distilled-1.4M-English
max_seq_length: 32768
gradient_checkpointing: true
preprocessing_num_workers: 128
per_device_train_batch_size: 1 
gradient_accumulation_steps: 4 # effective batch size 128 with 4 nodes
learning_rate: 5.0e-05
lr_scheduler_type: linear
warmup_ratio: 0.1
weight_decay: 0.0001
num_train_epochs: 3
output_dir: outputs/sft/instella-3b-sft-math-stage2
report_to:
  - wandb
logging_steps: 1
dataset_config_name: "default"
reduce_loss: sum
checkpointing_steps: 5000
dataset_mix_dir: outputs/data
hf_metadata_dataset: allenai/olmo-instruct-evals
add_bos: true
exp_name: instella-3b-sft-math-stage2
keep_last_n_checkpoints: 10